# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'master_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MasterWindow(object):
    def setupUi(self, MasterWindow):
        MasterWindow.setObjectName(_fromUtf8("MasterWindow"))
        MasterWindow.resize(1000, 700)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/698/698.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MasterWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MasterWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.test_b = QtGui.QPushButton(self.centralwidget)
        self.test_b.setObjectName(_fromUtf8("test_b"))
        self.horizontalLayout.addWidget(self.test_b)
        self.test_b_2 = QtGui.QPushButton(self.centralwidget)
        self.test_b_2.setObjectName(_fromUtf8("test_b_2"))
        self.horizontalLayout.addWidget(self.test_b_2)
        self.clr_b = QtGui.QPushButton(self.centralwidget)
        self.clr_b.setObjectName(_fromUtf8("clr_b"))
        self.horizontalLayout.addWidget(self.clr_b)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tmn_table = QtGui.QTableWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.tmn_table.sizePolicy().hasHeightForWidth())
        self.tmn_table.setSizePolicy(sizePolicy)
        self.tmn_table.setMinimumSize(QtCore.QSize(210, 0))
        self.tmn_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tmn_table.setBaseSize(QtCore.QSize(0, 0))
        self.tmn_table.setAlternatingRowColors(True)
        self.tmn_table.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tmn_table.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tmn_table.setObjectName(_fromUtf8("tmn_table"))
        self.tmn_table.setColumnCount(0)
        self.tmn_table.setRowCount(0)
        self.textBrowser = QtGui.QTextBrowser(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(210, 0))
        self.textBrowser.setAutoFillBackground(False)
        self.textBrowser.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser.setLineWidth(0)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.mes_table = QtGui.QTableWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mes_table.sizePolicy().hasHeightForWidth())
        self.mes_table.setSizePolicy(sizePolicy)
        self.mes_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.mes_table.setAlternatingRowColors(True)
        self.mes_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.mes_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.mes_table.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.mes_table.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.mes_table.setRowCount(0)
        self.mes_table.setObjectName(_fromUtf8("mes_table"))
        self.mes_table.setColumnCount(0)
        self.mes_table.horizontalHeader().setVisible(True)
        self.mes_table.horizontalHeader().setCascadingSectionResizes(False)
        self.mes_table.horizontalHeader().setDefaultSectionSize(120)
        self.mes_table.horizontalHeader().setHighlightSections(True)
        self.mes_table.horizontalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.splitter_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.always_top_cb = QtGui.QCheckBox(self.centralwidget)
        self.always_top_cb.setObjectName(_fromUtf8("always_top_cb"))
        self.horizontalLayout_2.addWidget(self.always_top_cb)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MasterWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MasterWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_3 = QtGui.QMenu(self.menubar)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        MasterWindow.setMenuBar(self.menubar)
        self.connect_menu = QtGui.QAction(MasterWindow)
        self.connect_menu.setObjectName(_fromUtf8("connect_menu"))
        self.param_menu = QtGui.QAction(MasterWindow)
        self.param_menu.setObjectName(_fromUtf8("param_menu"))
        self.collect_menu = QtGui.QAction(MasterWindow)
        self.collect_menu.setObjectName(_fromUtf8("collect_menu"))
        self.diy_menu = QtGui.QAction(MasterWindow)
        self.diy_menu.setObjectName(_fromUtf8("diy_menu"))
        self.about_menu = QtGui.QAction(MasterWindow)
        self.about_menu.setObjectName(_fromUtf8("about_menu"))
        self.menu.addAction(self.connect_menu)
        self.menu_2.addAction(self.param_menu)
        self.menu_2.addAction(self.collect_menu)
        self.menu_2.addAction(self.diy_menu)
        self.menu_3.addAction(self.about_menu)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MasterWindow)
        QtCore.QMetaObject.connectSlotsByName(MasterWindow)

    def retranslateUi(self, MasterWindow):
        MasterWindow.setWindowTitle(_translate("MasterWindow", "MainWindow", None))
        self.test_b.setText(_translate("MasterWindow", "test", None))
        self.test_b_2.setText(_translate("MasterWindow", "test", None))
        self.clr_b.setText(_translate("MasterWindow", "清空", None))
        self.textBrowser.setHtml(_translate("MasterWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">欢迎使用</p></body></html>", None))
        self.pushButton.setText(_translate("MasterWindow", "PushButton", None))
        self.pushButton_2.setText(_translate("MasterWindow", "PushButton", None))
        self.always_top_cb.setText(_translate("MasterWindow", "置顶", None))
        self.menu.setTitle(_translate("MasterWindow", "通信", None))
        self.menu_2.setTitle(_translate("MasterWindow", "常用命令", None))
        self.menu_3.setTitle(_translate("MasterWindow", "帮助", None))
        self.connect_menu.setText(_translate("MasterWindow", "连接（F1）", None))
        self.connect_menu.setShortcut(_translate("MasterWindow", "F1", None))
        self.param_menu.setText(_translate("MasterWindow", "参数读写", None))
        self.collect_menu.setText(_translate("MasterWindow", "采集监控", None))
        self.diy_menu.setText(_translate("MasterWindow", "自定义报文", None))
        self.about_menu.setText(_translate("MasterWindow", "关于", None))

import UI.icon_rc
